config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :edit_password
      patch :update_password
    end
  end
  get  '/signup', to: 'users#new'

  root 'static_pages#home'
  get '/terms', to: 'static_pages#terms'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

# ユーザーアカウントの管理
class User < ApplicationRecord
  has_one_attached :image

  attr_accessor :remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 50 }
  has_secure_password

  enum gender: { '' => '選択なし', '男性' => '男性', '女性' => '女性', 'その他' => 'その他', '答えたくない' => '答えたくない' }
  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: session_params[:username])

    if user&.authenticate(session_params[:password])
      log_in user
      flash[:success] = 'ログインしました。'
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    flash[:success] = 'ログアウトしました。'
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    if logged_in?
      redirect_to current_user
    end
  end

  def terms; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# ユーザーアカウントの管理
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update edit_password destroy]
  before_action :correct_user,   only: %i[edit update edit_password destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました。'
      redirect_back_or @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # if @user.update_attributes(user_params)
    if @user.update!(user_params)
      flash[:success] = 'アカウント情報を編集しました。'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def update_password
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_password_only)
      flash[:success] = 'パスワードを変更しました。'
      redirect_to @user
    else
      render 'edit_password_user'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'アカウントを削除しました。'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :website, :bio, :email,
                                 :phone_number, :gender, :password, :password_confirmation, :image)
  end

  def user_params_password_only
    params.require(:user).permit(:password, :password_confirmation)
  end

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'ログインしてください'
    redirect_to login_url
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'PictureSns'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークンcookieに対応するユーザーを返す
  # 現在ログインしているユーザーを返す (いる場合)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
p footer

app/views/layouts/application.html.slim
doctype html
html
  head
    title= full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

    

    .container
      .app-title.nav.navbar.navbar-expand-md
        = link_to "picture_sns", root_path, class: 'navbar-brand'
        ul.navbar-nav.navbar-right
          - if logged_in?
            li= link_to "Settings", edit_user_path(current_user)
            li= link_to "Index", users_path

      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")

      = yield
      .mt-5
        = debug(params) if Rails.env.development?
      
      = render 'layouts/footer' 

app/views/static_pages/home.html.slim
- provide(:title, "Home")
h1 StaticPages#home
p Find me in app/views/static_pages/home.html.slim

.flex-column.d-inline-flex
  = link_to  "新規登録する", signup_path, class: "btn btn-lg btn-primary mb-3" 
  = link_to  "ログインする", login_path, class: "btn btn-lg btn-primary mb-3" 

.d-flex.flex-column.bd-highlight.mb-4
  button.btn.btn-primary.col-3.mb-4 type="botton" Facebookログインボタン

= "#{logged_in?}"

app/views/static_pages/terms.html.slim
h1 利用規約
p ここに規約を書く

app/views/users/edit.html.slim
- provide(:title, "アカウント情報編集")

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control col-4', id: 'image'
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control col-4', id: 'user_name'
  .form-group
    = f.label :username
    = f.text_field :username, class: 'form-control col-4', id: 'user_username'
  .form-group
    = f.label :website
    = f.text_field :website, class: 'form-control col-4', id: 'user_website'
  .form-group
    = f.label :bio
    = f.text_area :bio, rows: 5, class: 'form-control col-4', id: 'user_bio'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control col-4', id: 'user_email'
  .form-group
    = f.label :phone_number
    = f.text_field :phone_number, class: 'form-control col-4', id: 'user_phone_number'
  .form-group    
    = f.label :gender
    = f.select(:gender, options_for_select(User.genders, selected: @user.gender), {}, {class: "form-control col-4"})
  = f.submit nil, class: 'btn btn-primary col-4 mb-5'

= link_to "アカウントを削除する", @user, method: :delete, data: { confirm: "アカウントを削除してもよろしいですか？" },  class: "btn btn-lg btn-danger mr-3" 

app/views/users/edit_password.html.slim
- provide(:title, 'パスワード変更')

h1 パスワード変更

= form_with model: @user,method: :patch, url: :update_password_user, local: true do |f|
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control col-4', id: 'user_password'
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control col-4', id: 'user_password_confirmation'
    
  = f.submit nil, class: 'btn btn-primary col-4 mb-5'

app/views/users/index.html.slim
- provide(:title, 'All users')
h1 All users
= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)

ul.users
  - @users.each do |user|
    li
      = link_to user.name, user
= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)

app/views/users/new.html.slim
- provide(:title, "アカウント作成")

h1 Sign up

- if @user.errors.present?
  ul#error_explanation
    - @user.errors.full_messages.reverse_each do |message|
      li= message

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control col-4', id: 'user_name'
  .form-group
    = f.label :username
    = f.text_field :username, class: 'form-control col-4', id: 'user_username'
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control col-4', id: 'user_password'
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control col-4', id: 'user_password_confirmation'

  = f.submit nil, class: 'btn btn-primary col-4 mb-5'


= link_to  '利用規約はコチラ', terms_path 

app/views/users/show.html.slim
h1 ユーザーの詳細

table.table.table-hover
  tbody
    tr
      th style="width:15%" = User.human_attribute_name(:id)
      td style="width:85%" = @user.id
    tr
      th= User.human_attribute_name(:image)      
      td= image_tag @user.image if @user.image.attached?
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:username)
      td= @user.username
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:website)
      td= @user.website
    tr
      th= User.human_attribute_name(:bio)
      td= @user.bio
    - if current_user?(@user)
      tr
        th= User.human_attribute_name(:phone_number)
        td= @user.phone_number
      tr
        th= User.human_attribute_name(:gender)
        td= @user.gender     
- if current_user?(@user)
  = link_to "ユーザー情報編集", edit_user_path, class: "btn btn-lg btn-primary mr-3" 
  = link_to "パスワード変更", edit_password_user_path, class: "btn btn-lg btn-primary mr-3" 
  = link_to "ログアウト", logout_path, method: :delete, class: "btn btn-lg btn-primary mr-3" 